# Generated by Django 4.1.2 on 2022-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=90)),
                ('parte', models.IntegerField()),
                ('video', models.URLField()),
                ('convocazione', models.FileField(upload_to='')),
                ('nota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YearFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(max_length=90)),
            ],
        ),
    ]
