# Generated by Django 4.1.2 on 2022-12-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearelement',
            name='anno',
            field=models.CharField(default=True, max_length=90),
            preserve_default=False,
        ),
    ]
