# Generated by Django 4.1.2 on 2023-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_yearelement_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearelement',
            name='nota',
            field=models.TextField(blank=True),
        ),
    ]
