# Generated by Django 4.1.2 on 2022-12-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ultimo_consiglio', models.CharField(max_length=90)),
                ('titolo_file', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
