# Generated by Django 4.1.2 on 2022-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='video_autoplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='video_mute',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='video_youtube',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
    ]
