# Generated by Django 4.1.2 on 2022-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homesettings_video_autoplay_homesettings_video_mute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesettings',
            name='video_youtube',
            field=models.CharField(max_length=4090),
        ),
    ]
