# Generated by Django 4.1.2 on 2023-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homesettings_video_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesettings',
            name='video_youtube',
            field=models.CharField(help_text='Link supported: <br>    · https://www.youtube.com/watch={id} <br>    · https://www.youtu.be/{id}', max_length=4090),
        ),
    ]
